[package]
name = "bom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
validate = { path = "../validate" }
validate_derive = { path = "../validate_derive" }